DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS film_mpa;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS mpa;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS friendship;
DROP TABLE IF EXISTS users_filmorate;

CREATE TABLE IF NOT EXISTS users_filmorate (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar NOT NULL,
  login varchar(255) NOT NULL,
  name varchar(255),
  birthday date,
  CONSTRAINT email_not_blank CHECK (email <> ''),
  CONSTRAINT login_not_blank CHECK (login <> ''),
  CONSTRAINT birthday_date CHECK (birthday <= CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS friendship (
  user1_id int,
  user2_id int,
  CONSTRAINT pk_friendship PRIMARY KEY (user1_id, user2_id)
);

CREATE TABLE IF NOT EXISTS film (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL,
  description varchar(200),
  release_date date,
  duration int,
  CONSTRAINT film_duration CHECK (duration > 0),
  CONSTRAINT film_date CHECK (release_date > date '1895-12-28'),
  CONSTRAINT name_not_blank CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS mpa (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255)
);

CREATE TABLE IF NOT EXISTS genre (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255)
);

CREATE TABLE IF NOT EXISTS film_genre (
  film_id int,
  genre_id int,
  CONSTRAINT pk_film_genre PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_mpa (
  film_id int,
  mpa_id int,
  CONSTRAINT pk_film_mpa PRIMARY KEY (film_id, mpa_id)
);

CREATE TABLE IF NOT EXISTS likes (
  film_id int,
  user_id int,
  CONSTRAINT pk_likes PRIMARY KEY (film_id, user_id)
);

ALTER TABLE friendship ADD FOREIGN KEY (user1_id) REFERENCES users_filmorate (id) ON DELETE CASCADE;

ALTER TABLE friendship ADD FOREIGN KEY (user2_id) REFERENCES users_filmorate (id) ON DELETE CASCADE;

ALTER TABLE film_genre ADD FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE;

ALTER TABLE film_genre ADD FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE;

ALTER TABLE film_mpa ADD FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE;

ALTER TABLE film_mpa ADD FOREIGN KEY (mpa_id) REFERENCES mpa (id) ON DELETE CASCADE;

ALTER TABLE likes ADD FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE;

ALTER TABLE likes ADD FOREIGN KEY (user_id) REFERENCES users_filmorate (id) ON DELETE CASCADE;